site_name: Woan Blog
site_description: Woan Blog
site_url: https://github.com/WoanSs
site_author: Woa

theme:
    name: material
    custom_dir: overrides
    icon:
      logo: fontawesome/solid/scroll 
    favicon: assets/meta/whale 02.png 
    font:
        text: JetBrains Mono
        code: JetBrains Mono
    language: en
    
    # palette:
      # # Light mode
      # - media: "(prefers-color-scheme: light)"
      #   scheme: default
      #   primary: deep purple
      #   accent: light blue
    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/link
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/toggle-switch-off
          name: Switch to system preference

        
    features:
      - search.suggest
      - search.highlight
      - navigation.footer

copyright: Copyright &copy; 2024 Woan 



plugins:
  - search
  # - roamlinks
  - autolinks
  - callouts
  # - meta:
  #     meta_file: .meta.yml
  - blogging:
      dirs:
        - post
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: ' %d-%m-%Y '

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      
  - toc:
      permalink: true



extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/yds.thienqc/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thienqc/
  analytics:
    provider: google
    property:
