site_name: thienqc
site_description: thienqc's blog
site_url: https://thienqc.github.io/blog/
site_author: thienqc

theme:
    name: 'material'
    icon:
      logo: fontawesome/solid/brain
      favicon: assets/meta/brain-solid.svg
    # font:
    #     text: Ubuntu
    #     code: Ubuntu Mono
    # language: en
    
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue grey
        accent: light blue
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue grey
        accent: light blue
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
  
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - search.suggest
        - search.highlight
        
# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 



extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/yds.thienqc/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thienqc/


# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - https://unpkg.com/mermaid/dist/mermaid.min.js 