site_name: thienqc
site_description: thienqc's blog
site_url: https://thienqc.github.io/blog/
site_author: thienqc

theme:
    name: 'material'
    icon:
      logo: fontawesome/solid/brain
      # favicon: assets/meta/brain-solid.png
    font:
        text: Roboto
        code: Roboto Mono
    language: vi
    
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: deep purple
        accent: light blue

plugins:
  - blogging:
      dirs:
        - blog

      categories:
        - name: reviews
          dirs:
            - reviews

      features:
        tags:
          index_page: tags.md
          insert: top


extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/yds.thienqc/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thienqc/
